# Site settings
title: Gardenlink
baseurl: ""
url: "https://gardenlink.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
